[원찬희] sprint2
codeit-bootcamp-frontend/6-Sprint-Mission pull request #132
Opened 2024-03-22 13:59 UTC by wch2208

## 요구사항

### 해당 미션 피그마 링크
https://www.figma.com/file/IVkRlYWHY74QlgmxqA99Ym/%EC%8A%A4%ED%94%84%EB%A6%B0%ED%8A%B8-%EB%AF%B8%EC%85%98?type=design&node-id=338-13426&mode=design&t=4dXAPMwnuWOCuIYc-0

**로그인 페이지, 회원가입 페이지 공통**

- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 아래로 스크롤 해도 상단 네비게이션 바(Global Navigation Bar)가 최상단에 고정됩니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 #3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.
- [x] SNS 아이콘들은 클릭시 각각 실제 서비스 홈페이지로 이동합니다.

**로그인 페이지**

- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

**회원가입 페이지**

- [x] “로그인”버튼 클릭 시 “/signin” 페이지로 이동합니다.

## **체크리스트 [심화]**

- [x] palette에 있는 color값들을 css 변수로 등록하고 사용해 주세요.
- [x] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 아이콘을 추가해 주세요.

**로그인 페이지, 회원가입 페이지 공통**

- [x] “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x] 아래로 스크롤 해도 상단 네비게이션 바(Global Navigation Bar)가 최상단에 고정됩니다.
- [x] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x] input 요소에 focus in 일 때, 테두리 색상은 #3692FF입니다.
- [x] input 요소에 focus out 일 때, 테두리는 없습니다.
- [x] SNS 아이콘들은 클릭시 각각 실제 서비스 홈페이지로 이동합니다.

**로그인 페이지**

- [x] “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

**회원가입 페이지**

- [x] “로그인”버튼 클릭 시 “/signin” 페이지로 이동합니다.

## **체크리스트 [심화]**

- [x] palette에 있는 color값들을 css 변수로 등록하고 사용해 주세요.
- [x] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 아이콘을 추가해 주세요.

## 주요 변경사항

- 로그인 페이지 추가
- 회원가입 페이지 추가

## 테스트 방법

### 배포 주소

https://sprint-mission2-chanhee.netlify.app/

### 깃헙 레포지토리 링크

https://github.com/wch2208/6-Sprint-Mission/tree/part1-원찬희-sprint2

## 스크린샷

![pr1](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/97877328/19a7681f-99c7-470e-807d-4c4733e68615)
![pr2](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/97877328/1cf7fc8c-0cb8-4217-8bca-f7b29f22c590)

## 멘토에게

- 주요 작업 사항인 페이지 마크업을 마치고 커밋하기 전에 홈화면에 헤더의 수정 사항이 눈에 보여서 수정한 경우 커밋 메세지 타입이 feat, refactor가 동시에 포함되는데 어찌 처리하는게 좋을까요? 마진 값을 수정한 정도라서 특별히 커밋내용을 추가하진 않았습니다.

2024-03-24 15:20 UTC, wonsss commented
@wch2208 찬희님 PR에서 conflict가 발생하여 merge할 수 있는 상태가 아니에요. 😢 
sprint 1 merge 후, merge된 base branch를 찬희님의 fork된 repo에 sync 후 해당 브랜치를 베이스로 새 브랜치를 만들어 PR을 올리셨어야 했는데, 그렇지 않아서 이와 같은 충돌이 발생했을 것 같네요.
이러한 충돌이 협업 시에 종종 발생하기 때문에, 이번 기회에 해결방법까지 알아보시면 좋겠네요.
![image](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/59413128/29ac0979-a49d-45b8-ad2e-e0b67e2c5f3f)

2024-03-24 15:33 UTC, wonsss requested changes
찬희님 안녕하세요! sprint 2 미션도 잘 진행해주셨네요 👍 

그런데 참고로 현재 찬희님 PR에서 conflict가 발생하여 merge할 수 있는 상태가 아니에요. 😢 
sprint 1 merge 후, merge된 base branch를 찬희님의 fork된 repo에 sync 후 해당 브랜치를 베이스로 새 브랜치를 만들어 PR을 올리셨어야 했는데, 그렇지 않아서 이와 같은 충돌이 발생했을 것 같네요.
이러한 충돌이 협업 시에 종종 발생하기 때문에, 이번 기회에 해결방법까지 알아보시면 좋겠어요. 충돌 해결 후 재리뷰 요청 부탁드립니다.
![image](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/59413128/29ac0979-a49d-45b8-ad2e-e0b67e2c5f3f)

2024-03-24 15:33 UTC, wonsss commented on index.html
> +          <img src="/assets/heroImg.svg" class="hero_img" alt="" />
alt 속성 값을 비우신 이유가 있으실까요?

2024-03-24 15:33 UTC, wonsss commented on index.html
> +    <!-- header, 상단 로고와 로그인 버튼 -->
주석이 맥락 파악에 꼭 필요하진 않다면, 개발 후 제거해주시는 것이 더 깔끔할 것 같아요.

2024-03-24 15:33 UTC, wonsss commented on index.html
> +            <p class="logo_title">판다마켓</p>
p 태그와 span 태그의 차이점은 무엇일까요?

참고링크: https://inpa.tistory.com/entry/HTML-%F0%9F%93%9A-p-div-span-%ED%83%9C%EA%B7%B8-%EC%A0%95%EB%A6%AC#%E2%80%8B%3Cp%3E

2024-03-24 15:33 UTC, wonsss commented on index.html
> +          <article class="hot_item_contnet">
section과 article 요소는 각각 어떤 경우에 사용할까요?

2024-03-24 15:33 UTC, wonsss commented on index.html
> +            >
👍

2024-03-24 15:33 UTC, wonsss commented on signin.html
> +          <input placeholder="이메일을 입력해주세요" type="email" />
label과 input을 연관시킬 수 있습니다. 연관시키게 되면 label 클릭 시 연관된 input에 focus 가게 되어 사용성이 더 좋아집니다. 웹접근성에도 도움이 되구요. 
> `<label>` 을 `<input>` 요소와 연관시키려면, `<input>` 에 id 속성을 넣어야합니다. 그런 다음 `<label>` 에 id 와 같은 값의 for 속성을 넣어야합니다.

참고: https://developer.mozilla.org/ko/docs/Web/HTML/Element/label

2024-03-24 15:33 UTC, wonsss commented on signin.html
> +              type="password"
input type 속성에 적절한 값을 다 잘 넣어주셨네요 👍 
이외에도 많은 input type들이 있는데, 참고해두시고 나중에 필요할 때 적절한 것을 쓰시길 바랄게요.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

2024-03-24 15:33 UTC, wonsss commented on signin.html
> +          <button type="submit" class="submit">로그인</button>
form에 대한 submit을 하기 위한 button에 type을 submit으로 잘 넣어주셨네요! 👍

2024-03-24 15:33 UTC, wonsss commented on signup.html
> +          <input placeholder="이메일을 입력해주세요" type="email" />
input 태그에 autofocus 속성을 주시면 페이지가 새로고침되자마자 이 첫 input에 focus가 있어서 사용자가 인풋을 클릭할 필요 없이 바로 입력할 수 있어서 사용자 경험에 좋을 것 같아요.

2024-03-24 15:33 UTC, wonsss commented on signup.html
> +    <meta charset="UTF-8" />
meta charset="utf-8" 의 의미와 필요성은 무엇일까요?

참고: https://antstudy.tistory.com/29

2024-03-25 05:01 UTC, wch2208 commented on index.html
> +          <img src="/assets/heroImg.svg" class="hero_img" alt="" />
의미 없는 장식용 이미지는 alt=""을 사용하면 리더기가 읽지 않고 넘어간다고 알고 있어서 이렇게 작성했는데요
생각해보니 무슨 그림이 존재한다고 알려주는게 맞는 것 같습니다.

2024-03-25 05:25 UTC, wch2208 commented on index.html
> +    <!-- header, 상단 로고와 로그인 버튼 -->
네 불필요한 주석은 제거하겠습니다!

2024-03-25 05:39 UTC, wch2208 commented on index.html
> +            <p class="logo_title">판다마켓</p>
p 태그: 단락(paragraph)을 정의하는 데 사용, 긴 텍스트 블록에 사용함
span 태그: 인라인 요소로, 텍스트의 일부분에 스타일이나 클래스를 적용할 때 사용

따라서 p -> span으로 수정하는 것이 좋다고 판단했습니다.

2024-03-25 06:08 UTC, wch2208 commented on index.html
> +          <article class="hot_item_contnet">
section: 구조적 요소로 콘텐츠의 그룹을 묶는다.
article: 독립적이고 완결적인 요소를 묶는다.

수정사항
- section은 구조적 요소이므로 main_guidline과 같은 의미를 가진다고 판단하여 div => section으로 수정하고 통합
- 본문의 내용은 반복적인 형태와 연결되는 메세지를 가진다고 판단하여 article => div로 변경

배운점
- 의미를 좀 더 면밀하게 구분해야겠습니다.

2024-03-25 06:15 UTC, wch2208 commented on index.html
> +            >
감사합니다!^^

2024-03-25 06:22 UTC, wch2208 commented on signin.html
> +          <input placeholder="이메일을 입력해주세요" type="email" />
로그인, 회원가입의 모든 input과 label에 적용했습니다

2024-03-25 06:27 UTC, wch2208 commented on signin.html
> +              type="password"
감사합니다! ^^

2024-03-25 06:28 UTC, wch2208 commented on signin.html
> +          <button type="submit" class="submit">로그인</button>
감사합니다!^^

2024-03-25 06:31 UTC, wch2208 commented on signup.html
> +          <input placeholder="이메일을 입력해주세요" type="email" />
로그인과 회원가입 페이지에 첫번째 input에 autofocus를 적용했습니다.
페이지 접속 시 이메일 입력을 클릭하는 한 단계가 생략됐습니다!

2024-03-25 06:51 UTC, wch2208 commented on signup.html
> +    <meta charset="UTF-8" />
<meta charset="UTF-8" />은 html 파일을 웹브라우저에 표시할 때 문자 인코딩 방식을 설정하는데 사용됩니다.
컴퓨터가 문자를 표시하는 방법과 인간이 보는 문자 표시하는 방법이 달라서 인코딩 절차가 필요합니다.
유니코드 문자 인코딩 체계로 인터넷에서 가장 범용적으로 사용되는 것이 UTF-8입니다.

제거하고 웹페이지를 실행해도 문자가 잘 나타났습니다만 이것은 서버나 웹브라우저에서 기본 설정으로 지정되어 있기 때문이라고 합니다. 그러나 다양한 환경을 고려하여 명시적으로 작성해주는 것이 좋다고 합니다.

2024-03-26 13:32 UTC, merged