[유예하] sprint2
codeit-bootcamp-frontend/6-Sprint-Mission pull request #143
Opened 2024-03-24 13:37 UTC by YehaYoo

## 요구사항
- [x]  Github에 PR(**P**ull **R**equest)을 만들어서 미션을 제출합니다.
- [x]  Netlify에 파일 배포가 아닌 포크한 Github 레포지토리로 연결합니다.
- [x]  피그마 디자인에 맞게 페이지를 만들어 주세요.
- [x]  React와 같은 UI 라이브러리를 사용하지 않고 진행합니다.

### 기본
      **로그인 페이지, 회원가입 페이지 공통**
- [x]  “판다마켓" 로고 클릭 시 루트 페이지(“/”)로 이동합니다.
- [x]  로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일합니다.
- [x]  input 요소에 focus in 일 때, 테두리 색상은 #3692FF입니다.
- [x]  input 요소에 focus out 일 때, 테두리는 없습니다.
- [x]  SNS 아이콘들은 클릭시 각각 실제 서비스 홈페이지로 이동합니다.

**로그인 페이지**

- [x]  “회원가입”버튼 클릭 시 “/signup” 페이지로 이동합니다.

**회원가입 페이지**

- [x]  “로그인”버튼 클릭 시 “/signin” 페이지로 이동합니다.

### 심화

- [x]  palette에 있는 color값들을 css 변수로 등록하고 사용해 주세요.
- [x]  비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 아이콘을 추가해 주세요.

## 주요 변경사항
- X

## 스크린샷

![image](https://github.com/YehaYoo/test/assets/151544448/524ab3f3-b503-4451-87d4-07f96a598c6d)
![image](https://github.com/YehaYoo/test/assets/151544448/611c9bde-23fe-4d87-a385-2a68c743602b)
![image](https://github.com/YehaYoo/test/assets/151544448/bf992693-1be0-420e-ba97-71752a743325)
![image](https://github.com/YehaYoo/test/assets/151544448/f6e8003b-b970-4673-9781-6ea19b2daa9e)
![image](https://github.com/YehaYoo/test/assets/151544448/0c52f479-42c4-48aa-a2aa-38e9819f1817)

## 멘토에게

- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-03-24 16:07 UTC, wonsss requested changes
안녕하세요~ 예하님 😄 
스프린트 미션을 잘 해주셨네요 👍 수고 많으셨습니다.
커밋도 깔끔하게 적절한 단위와 메세지로 잘 남겨주셨습니다.

아래와 같이 PR 본문 템플릿에 몇 가지 추가를 하였는데, 이렇게 조금 더 자세한 PR 설명을 전달해주시는 습관을 지금부터 길러보시면 현업에서도 도움이 되실 거예요. 😄 
```plain
## 요구사항
### 해당 미션 피그마 링크

### 기본
- []

### 심화
- []

## 주요 변경사항

## 테스트 방법
### 배포 주소

### 로컬 테스트 방법
// 프로젝트 설치 및 실행 명령어와 로컬 실행 시 테스트 가능한 링크 주소

## 스크린샷
// 주요 변경사항에 대한 스크린샷

## 멘토에게

```

리뷰 참고 부탁드려요 😄

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +</html>
<img width="147" alt="image" src="https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/59413128/ca0a6e3f-a680-4463-9692-cd22e0a7f6a5">

파일 내 코드 마지막 줄 뒤에 개행을 하지 않으면, 이와 같이 빨간색 금지 모양의 아이콘이 표시됩니다. 이는 "End Of Line(EOL)" 이 없다는 경고입니다. 이를 없애려면 파일 내 코드 마지막 줄 뒤에 개행을 해주셔야 해요.

그렇다면 End Of Line 은 왜 필요할까요? 아래 설명을 참고해보세요. 😄 
그리고 나중에 prettier를 설치하게 되면, 매번 귀찮게 파일 마지막 줄에 개행할 필요 없이, 파일 저장할 때마다 자동으로 개행이 추가되도록 formatting을 할 수 있어요~

> 여러 버전의 유닉스 OS간의 공통된 API 및 인터페이스를 정의해놓은 POSIX 명세 중 text file 부분을 보면 유닉스 시스템은 text file들을 서로 구분할때 EOL을 사용하기 때문에 파일을 만들때마다 파일의 끝에 EOL을 넣어주는 것이 안전하다.
구현하는 방법은 항상 파일 작성이 끝나면 엔터키를 통해 맨 아래줄에 공백을 만들어주거나, 프리티어를 통해 저장시 자동으로 파일 맨 끝에 개행이 되게끔 하는 방법이 있다.
https://avocado12-note.tistory.com/11

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +  <meta charset="UTF-8">
meta charset="utf-8" 의미와 필요성은 무엇일까요?
참고링크: https://antstudy.tistory.com/29

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +<html>
html 요소에 lang 속성은 요소의 특성 값과 텍스트 내용의 기본 언어를 가져오거나 설정해요.  
한국어 사용자 대상으로 하는 사이트이므로 lang 속성의 값으로 "ko"를 넣어주시면 좋아요. 😄 

참고: [https://developer.mozilla.org/ko/docs/Web/API/HTMLElement/lang](https://developer.mozilla.org/ko/docs/Web/API/HTMLElement/lang)

https://r12a.github.io/app-subtags/

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +<head>
head 요소 내에 viewport meta tag도 추가해주세요. 😄 이 태그는 반응형 웹 디자인에서 중요한 역할을 해요.  뷰포트의 크기, 축척 및 초기 화면 배율을 지정하며, 자세한 내용은 아래 MDN 문서를 참고해보세요.

참고: https://developer.mozilla.org/ko/docs/Web/HTML/Viewport_meta_tag

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +            <img alt="google" src="/assets/google.png">
img 태그에 alt 속성을 잘 적용해주셨네요. 👍  다음과 같은 이유로 img 태그에 시각 장애인분께 들릴 해당 이미지를 설명하는 문구가 무엇이면 좋을지 고민하며 적절한 값을 넣어주는 것이 좋습니다. 
> img 태그의 alt 속성은 이미지를 보여줄 수 없을 때 해당 이미지를 대체할 텍스트를 명시합니다.
이러한 alt 속성은 사용자가 느린 네트워크 환경이나 src 속성값의 오류, 시각 장애인용 스크린 리더의 사용 등 어떤 이유로든 사용자가 이미지를 볼 수 없을 때 이미지 대신 제공할 대체 정보를 제공합니다.

https://ko.wikipedia.org/wiki/Alt_%EC%86%8D%EC%84%B1

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +        <div>간편 로그인하기</div>
간단한 텍스트 하나를 표시할 때도, div, p, span 요소 중 적절한 것 하나를 택할 수 있어요.
div, p, span 요소의 차이가 무엇일까요? 
아래 링크 참고해보세요. 😄 

참고링크: https://inpa.tistory.com/entry/HTML-%F0%9F%93%9A-p-div-span-%ED%83%9C%EA%B7%B8-%EC%A0%95%EB%A6%AC#%E2%80%8B%3Cp%3E

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +      <button class="signin-button">로그인</button>
각 버튼에 button type을 알맞게 지정해주셨네요.

로그인 버튼에는 type을 생략해주셨는데, button 태그의 type 속성의 기본값은 submit입니다. 해당 로그인 버튼은 form submit 하기 위한 button이므로  기본값인 submit을 그대로 쓰므로 이렇게 생략해주셔도 괜찮습니다. 다만, 명시적으로 type을 넣어주시는 것도 괜찮다고 생각해요.

그리고 참고로 양식 제출용 버튼이 아니라면 type 특성을 button으로 지정하는걸 잊지 마세요. 기본값에서는 버튼을 눌렀을 때 양식 데이터를 제출하고, (존재하지 않는) 응답을 불러오려고 시도하는 과정에서 문서의 현재 상태가 사라질 수 있습니다.

>  button 태그의 type 속성: 버튼의 행동 방식. 가능한 값은 다음과 같습니다.
-submit: 버튼이 서버로 양식 데이터를 제출합니다. 지정하지 않은 경우 기본값이며, 유효하지 않은 값일 때도 사용합니다.
-reset: <input type="reset">처럼, 모든 컨트롤을 초깃값으로 되돌립니다.
-button: 기본 행동이 없으며 클릭했을 때 아무것도 하지 않습니다. 클라이언트측 스크립트와 연결할 수 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/button

2024-03-24 16:07 UTC, wonsss commented on signin.html
> +      />
label과 input을 연관시켜주세요. 연관시키면, label 클릭 시 연관된 input에 focus 가게 되어 사용성이 더 좋아집니다. 웹접근성에도 도움이 되구요. 
> `<label>` 을 `<input>` 요소와 연관시키려면, `<input>` 에 id 속성을 넣어야합니다. 그런 다음 `<label>` 에 id 와 같은 값의 for 속성을 넣어야합니다.

참고: https://developer.mozilla.org/ko/docs/Web/HTML/Element/label

2024-03-24 16:07 UTC, wonsss commented on signup.html
> +      />
input 태그에 autofocus 속성을 주시면 페이지가 새로고침되자마자 이 첫 input에 focus가 있어서 사용자가 인풋을 클릭할 필요 없이 바로 입력할 수 있어서 사용자 경험에 좋을 것 같아요.

<img width="923" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/799de619-e497-4137-b355-7e4c7a8301ce">

2024-03-24 16:07 UTC, wonsss commented on index.html
> +        </a>
a 태그에 target="_blank" 속성을 사용할 때는 rel="noopener noreferrer" 특성을 지정하여 window.opener 참조 설정을 방지하는 것이 좋습니다. 이를 통해 생성된 창의 opener 속성에 접근해도 null을 반환합니다.  하이퍼링크를 신뢰할 수 없을 때, 브라우저의 보안 리스크를 방지할 수 있습니다.

관련해서 참고하실 수 있는 링크 전달드립니다.
https://mathiasbynens.github.io/rel-noopener/#recommendations
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

2024-03-24 16:07 UTC, wonsss commented on index.html
> +      <button class="header-button" type="button" onclick="location.href='/items.html'">
button 요소의 type 속성의 값으로 "button"을 잘 적용해주셨네요 👍

2024-03-24 16:07 UTC, wonsss commented on CSS/reset.css
CSS 리셋을 잘 하셨네요 👍 
이러한 CSS 리셋 또는 normalize가 왜 필요한지에 대해 이해하시면 좋아요.
CSS 리셋은 일관성 없는 다양한 브라우저의 기본 스타일을 초기화하는 목적으로 사용한답니다.
크롬, 사파리, 파이어폭스, 삼성인터넷 등 많은 브라우저들이 각각 HTML 태그에 대한 스타일 기본값이 다르므로 그 차이를 없애기 위해 필요해요. 
즉, 크로스 브라우징을 위해 필요합니다.
웹 개발에서 "크로스 브라우징"도 매우 중요한 부분입니다.

그리고 참고로 CSS Reset에서 각 설정이 이유가 무엇인지 아래 링크 통해서 확인해보세요.
- 참고
[(번역) (더) 최신의 CSS Reset](https://ykss.netlify.app/translation/a_more_modern_css_reset/)

2024-03-24 16:07 UTC, wonsss commented on CSS/signin-style.css
> +}
이렇게 box-sizing에 border-box 속성을 지정하는 이유는 무엇일까요?  
기본값은 content-box인데 무슨 차이가 있을까요? 관련 내용에 대해 정확히 알아두시면 좋습니다. 😄  
[https://developer.mozilla.org/ko/docs/Web/CSS/box-sizing](https://developer.mozilla.org/ko/docs/Web/CSS/box-sizing)

2024-03-24 16:07 UTC, wonsss commented on CSS/signin-style.css
> +}
CSS 변수를 잘 사용하셨네요 👍

2024-03-24 16:07 UTC, wonsss commented on CSS/styles.css
> +}
signin-style.css와 styles.css에서 중복되는 부분이 있는 것 같은데, 이처럼 모든 페이지에서 공통으로 적용되어야 하는 css가 있다면 global.css 같은 파일을 만들어 분리해서 사용하실 수 있을 것 같아요   😄

2024-03-25 05:14 UTC, YehaYoo commented on signin.html
> +</html>
확인했습니다!! 커밋 봤을 때 무슨 표시인가 했어요ㅠㅠ 덕분에 컴퓨터가 파일을 구분하는 방식이 있다는 것을 인지하게 되었습니다 :)

2024-03-25 10:53 UTC, YehaYoo commented on signin.html
> +</html>
[50a2274](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/50a2274644137fcb693d1b40cae77db0c18bea2d)

2024-03-25 11:06 UTC, YehaYoo commented on signin.html
> +<html>
lang 속성을 넣어야 스크린 리더와 검색 엔진이 언어를 파악할 수 있겠네요. 링크 잘 참고하도록 하겠습니다!
 [ecff08a](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/ecff08a467473384978dc73907bb8ae871028fc3) - 수정완료했습니다.

2024-03-25 11:24 UTC, YehaYoo commented on signin.html
> +<head>
문서 참고했습니다. 기본적으로 신경써야 할 부분이네요!
[5f6e3d7](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/5f6e3d7a814a896cd3bd7eb75061501e1f19f4d7) - 수정 완료했습니다.

2024-03-25 11:42 UTC, YehaYoo commented on signin.html
> +        <div>간편 로그인하기</div>
안 그래도 각 요소들에 대해 스스로 정리해보고 싶었는데 못했어요ㅠㅠㅠ 링크된 글 잘 참고하도록 하겠습니다!!

2024-03-25 12:19 UTC, YehaYoo commented on signin.html
> +      />
강의에 나왔던 내용인데 놓쳤네요! signin.html, signup.html수정완료했습니다.
[b18afd2](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/b18afd254bb88c7aa221e5b02d1fa53329990e6f)

2024-03-25 12:26 UTC, YehaYoo commented on signup.html
> +      />
정말 그렇겠네요!! signin.html, signup.html 둘 다 적용했습니다!
[41740a1](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/41740a1ac9a64e85ff2bf032c4fe598042f7cc31)

2024-03-25 12:54 UTC, YehaYoo commented on index.html
> +        </a>
웹 페이지를 제작할 때 단순히 기능을 구현하는 것만이 목적이 아니라 고려해야 할 부분이 많네요! 당연한 사실이지만 또 실감하게 되었습니다! 링크 참고하도록 하겠습니다.
[cd87d4e](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/cd87d4e70b43b2a741eb71bf8dd677932ab1ef1f) - 수정 완료했습니다.

2024-03-25 13:47 UTC, YehaYoo commented on CSS/styles.css
> +}
확인했습니다!
[b074160](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/b07416049f4b4b1f1eb1c4b3a116ed5e32c3e4cd) - global.css 추가

[630c5f8](https://github.com/YehaYoo/6-Sprint-Mission/pull/1/commits/630c5f881f048d9feff0341b619e48c98ece0abd) - global.css에 @import reset.css 

이 내용과 상관없이, 커밋 컨벤션을 적용할 때 태그가 대문자와 소문자 중 어느 것으로 시작해야하는지 궁금합니다. 지금은 우선 일관성만 유지하면 될까요?

2024-03-26 13:31 UTC, wonsss commented on CSS/styles.css
> +}
저는 커밋메세지 소문자로 하긴 합니다 ㅎㅎ 중요한 부분은 아니라서 일관성 있게 하시면 돼요.

2024-03-26 13:31 UTC, merged