[김보미] Sprint6
codeit-bootcamp-frontend/6-Sprint-Mission pull request #4
Opened 2024-03-14 05:15 UTC by Kbomi16

## 요구사항

### 기본
https://part1-kimbomi-sprint6.netlify.app/
- [x]랜딩 페이지의 url path는 루트(‘/’)로 설정합니다.
- [x]title은 “판다마켓”로 설정합니다.
- [x]화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 합니다.
- [x]화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px“로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소간 거리가 가까워지도록 설정합니다.
- [x]클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 CSS 속성 cursor: pointer 로 설정합니다.
- [x]“판다마켓” 클릭 시 루트 페이지(‘/’)로 이동합니다.
- [x]'로그인'버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지)
- [x]“구경하러가기”버튼 클릭 시(’/items’)로 이동합니다.(빈 페이지)
- [x]“Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ [v]페이지(‘/faq’)로 이동합니다.(모두 빈 페이지)
- [x]페이스북, 트위터, 유튜브, 인스타그램 아이콘을 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동합니다.

### 심화

- [x]palette에 있는 color값들을 css 변수로 등록하고 사용해 주세요.

## 주요 변경사항

- 링크 연결
- 반응형 페이지
- 화면 줄였을 때, main의 search 부분에서 이미지와 텍스트 순서 바꿈

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/88658551/b4ceb3f3-6062-45aa-a35f-21854e301048)
![image](https://github.com/codeit-bootcamp-frontend/6-Sprint-Mission/assets/88658551/37145876-2254-4596-8269-533aa10987c8)

## 멘토에게

-

2024-03-17 04:27 UTC, ddongule requested changes
안녕하세요 보미님~! 

작성해주신 코드 잘 확인했습니다! 👏👏 빠르게 잘 구현해주셨네요!
요구사항에 관한 내용도 살펴봤는데, 별건 아니지만 요구사항이랑 살짝 달라서 한번 확인해보시면 좋을 것 같아요.
- '로그인'버튼 클릭 시 로그인 페이지(‘/login’)로 이동합니다 (빈 페이지) 
   → `signin` 페이지로 연결되어용

또, 요 [commit message 규칙](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13)도 한번 살펴보시고 차근차근 적용해보시는 것두 추천드립니다! 👍

고생하셨어요!

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +  </a>
같은 레벨의 태그에서 indent 가 안맞고 있는 것같은데 prettier 설정 한번 살펴보시면 좋을 것 같아요!
파일 저장할 때마다 정리해주는 format on save 쪽 살펴보시면 될거에요! 🤸

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +    <a href="./signin.html"><button id="btn_small">로그인</button></a>
button tag와 a tag를 같이 사용하신 이유가 있을까용~? 두 태그 모두 이벤트가 발생하는 태그여서, 같이 사용하시게되면 두 이벤트가 서로 충돌하면서 하나의 이벤트가 무시되거나 제대로 동작하지 않는 문제가 발생할 수 있어요. (물론 지금은 a 태그에만 이벤트를 달아주셔서 문제가 발생하지는 않겠지만요!)

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +</html>
🙋‍♀️ eof (end of file) 이슈가 있네요! 프로그램을 돌릴 때 문제가 생기지는 않지만 관행적으로 사용되는 부분이라 확인해주시면 좋을 것 같아요! 요부분도 prettier나 lint 설정에서 마지막 줄에 개행문자를 넣어줄 수 있어요. ㅎㅎ

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +/* 색상 css 변수 */
지금은 하나의 페이지만 있어서 큰 문제가 없겠지만, 
앞으로 점차 파일이 늘어날수록 css 파일도 비대해지게 될텐데요, 어떻게 하면 파일을 잘 분리할 수 있을지 고민해보시는 것두 좋을 것 같아요! 🚀

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +}
전반적으로 가독성을 위해 스타일 사이에 개행이 있으면 좋을 것 같아요! 🌳

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +      <img src="./img/img_home_03.png" alt="home1" class="imgs">
이미지는 다른데 alt message가 똑같네요! 
만약 이미지를 볼 수 없는 상황이라면 요 대체텍스트를 통해 어떤 이미지를 가리키고있는지 알아낼 수 있어야 하는데, 텍스트가 같다면 같은 이미지라고 생각할 수 있을 것 같아요! 
웹 접근성에 대해서도 한번 찾아보시면 도움되실고에용! 🚀 ([참고 아티클](https://dev.to/bellatrick/mastering-web-accessibility-a-guide-for-frontend-developers-48ad))

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +      <img src="./img/img_home_top.png" class="home_img1" alt="메인이미지1">
보통 html tag는 열리고 닫는 태그를 항상 함께 사용해주는데요, 이렇게 굳이 닫는 태그가 필요없는 부분들은 `<img />` 처럼 self-closing tag로 사용해준답니당! ☺️

```html
      <img src="./img/img_home_top.png" class="home_img1" alt="메인이미지1" />
```

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +      <img src="./img/img_home_01.png" alt="home1" class="imgs">
class 이름이 조금 더 명확한 이름이면 좋을 것 같아요. `imgs` 는 범용적으로 모든 이미지들에게 사용될 수 있는 이름이라고 생각돼서요! 어떻게 생각하시나요~? 🚗

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +}
변수 등록해서 사용하시는거 완존 좋아용 👏👏

2024-03-17 04:27 UTC, ddongule commented on part1/index.html
> +      <img src="./img/img_home_top.png" class="home_img1" alt="메인이미지1">
🦖 class는 여러 element에 스타일링 할 수 있는 반면에 id는 딱 하나의 element에만 사용할 수 있어요. 
만약 요 페이지 내에서 또다른 small button 혹은 large button 을 사용하고자 할 때에는 어떻게 할 수 있을까용~?

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +}
모든 버튼에 기본적으로 들어가야하는 스타일링이라면 button:hover 속성에 요 속성을 주어도 될 것 같아요! 🙋‍♀️ 
그렇지 않다면 슥 넘어가셔두 좋습니다 ㅎㅎ

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +  font-size: 16px;
px / rem을 함께 사용해주고 계신데요, 어떤 기준으로 사용하고 계신지 알고싶어요!

2024-03-17 04:27 UTC, ddongule commented on part1/style.css
> +/* a태그 텍스트 스타일 제거 */
요렇게 주석을 다셔도 좋지만, 현업에서는 주석은 정말 정말 필요한 경우가 아니라면 달지 않는 것이 권장되어요 홍홍

2024-03-18 04:31 UTC, closed without merging

2024-03-18 07:21 UTC, Kbomi16 commented on part1/style.css
> +  font-size: 16px;
원래  rem을 쓰는데 혼자 정하기 애매한 크기들은 피그마 시안에 나와있는 width, height를 그대로 써서 px를 쓰게 되었습니다...!