[최수형] Sprint 1
codeit-bootcamp-frontend/6-Sprint-Mission pull request #7
Opened 2024-03-14 06:18 UTC by User850413

## 요구사항

### 기본

- [x] 디자인 구현
- [x] 랜딩 페이지의 url path는 루트(‘/’) 입니다.
- [x] title은 “판다마켓”으로 설정해 주세요.
- [x] 화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 해주세요.
- [x] 화면의 너비가 1920px 보다 작아질 때, “판다마켓” 로고의 왼쪽 여백 200px“로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소간 거리가 가까워지도록 해주세요.
- [x] 클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 cursor: pointer를 설정해 주세요.
- [x] “판다마켓” 클릭 시 루트 페이지(‘/’)로 이동시켜주세요.
- [x] “로그인”버튼 클릭 시 로그인 페이지(‘/signin’)로 이동합니다
- [x] “구경하러가기”버튼 클릭 시(’/items’)로 이동합니다.
- [x] 페이스북, 트위터, 유튜브, 인스타그램 아이콘은 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동 합니다.
- [x] “Privacy Policy”, “FAQ”는 클릭 시 각각 다음 페이지로 이동합니다 (Privacy 페이지(‘/privacy’)  /  FAQ 페이지(‘/faq’))

### 심화

- [x] 사용자의 브라우저가 크고 작아짐에 따라 페이지의 요소간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 보세요.(설정값은 자유입니다)

## 주요 변경사항

- html 작성
- css 작성
- 반응형 웹 작성

2024-03-14 11:00 UTC, User850413 commented
ㅁㄴㅇㄹ

2024-03-17 06:00 UTC, ddongule requested changes
안녕하세요 수형님! 
구현해주신 코드와 배포해주신 사이트 잘 봤습니다! 🤸
전반적으로 반응형도 잘 구현되어있고, 군더더기 없이 잘 만들어주신 것 같아요. 또 grid, reset-css, css variables 등의 다양한 속성을 사용하신 점도 인상깊었어요. 👍

멘토링에서 잠깐 이야기드렸던 [commit message 규칙](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13) 한번 보시고, 다음 커밋부터는 조금 더 세분화되고 구체적인 커밋 메시지가 있으면 더 좋을 것 같아요! 

이외에 몇가지 코멘트 남겨드렸는데, 확인해보시면 좋을 것 같아요.
고생하셨습니다~!

2024-03-17 06:00 UTC, ddongule commented on README.md
> +# 코드잇 스프린트 6기 프로젝트
readme 너무 깔끔하고 좋네요! 🥹

2024-03-17 06:00 UTC, ddongule commented on README.md
> +- Netlify 배포 시 한글이 깨지는 현상이 있었는데, 주의해야 할 것 같다.
💯

2024-03-17 06:00 UTC, ddongule commented on css/index.css
> +/* 메인 */
주석을 통해 어떤 부분에 대한 스타일인지 나타내어 주신 부분 넘 좋네요. 👍
다음 스텝으로는 더 세부적인 파일 분리도 한번 도전해보시는 것도 좋을 것 같습니당!

2024-03-17 06:00 UTC, ddongule commented on css/index.css
> +body {
가독성 차원에서 각 스타일 사이에 개행이 있으면 더 좋을 것 같아요. 요런 부분은 vscode prettier 설정을 통해 녹여낼 수 있을 것 같아요! 🚗

2024-03-17 06:00 UTC, ddongule commented on css/reset.css
> +@import url("https://cdn.jsdelivr.net/npm/fonts-archive-rokafsans/ROKAFSans.css");
reset css까지 👍

2024-03-17 06:00 UTC, ddongule commented on css/style.css
> +/* Style */
단순한 궁금증인데, index.css와 style.css를 나누신 기준이 궁금해요! 😎
style.css가 조금 더 넓은 범위의 스타일이고, index.css는 더 구체적인 스타일을 구현하고자 하신 것 같은데, 맞을까용?!

2024-03-17 06:00 UTC, ddongule commented on css/index.css
> +}
오오 혹시 파일 포맷의 차이점도 알고계신가요? svg 파일을 사용하셨네요! 👏 좋습니다!

2024-03-17 06:00 UTC, ddongule commented on css/index.css
> +.item:nth-child(2n-1) {
🚀

2024-03-17 06:00 UTC, ddongule commented on index.html
> +          ></a>
요런 부분은 self-closing 태그를 사용할 수도 있답니당! 
```suggestion
          <a
            href="https://www.facebook.com/"
            class="facebook"
            aria-label="facebook"
            target="_blank"
          />
```

2024-03-17 06:00 UTC, ddongule commented on index.html
> +          <img src="images/panda_top.svg" class="visual__bg" alt="" />
접근성 측면에서 alt tag는 꼭 붙여주는게 좋답니당! 🥹 ([관련 아티클](https://designlog.org/2512732#:~:text=%EB%8C%80%EC%B2%B4%20%ED%85%8D%EC%8A%A4%ED%8A%B8(Alt%20Tag)%EB%8A%94%20%EC%8B%9C%EA%B0%81%20%EC%9E%A5%EC%95%A0%EA%B0%80%20%EC%9E%88%EB%8A%94%20%EC%82%AC%EC%9A%A9%EC%9E%90%EC%99%80,%EB%A5%BC%20%ED%95%B4%EC%84%9D%ED%95%98%EB%8A%94%EB%8D%B0%20%EC%82%AC%EC%9A%A9%ED%95%9C%EB%8B%A4.))

2024-03-17 06:00 UTC, ddongule commented on css/style.css
> +}
rem, px을 함께 사용하셨는데 혹시 어떤 기준으로 px과 rem을 사용하고 계신지 궁금해요! 🙋‍♀️

2024-03-17 06:00 UTC, ddongule commented on css/style.css
> +  color: #666;
variables가 요런 부분들에도 적용되면 좋을 것 같아요!

2024-03-18 14:43 UTC, merged